package org.aerialpod.core.lan

/**
 * Authentication and encryption for the peer channel — the Kotlin half of
 * `lan/crypto.py`, byte for byte.
 *
 * Both ends hold the same pairing secret (see [Pairing]) and stretch it into a
 * 32-byte root key. A connection then runs a mutual challenge:
 *
 *     client -> server   {"v": 1, "cn": <16 random bytes>}
 *     server -> client   {"v": 1, "sn": <16 random bytes>}
 *     client -> server   {"proof": HMAC(K, "cli" | cn | sn)}      <- client first
 *     server -> client   {"proof": HMAC(K, "srv" | cn | sn)}
 *
 * This exchange is necessarily plaintext — no session key exists yet — so the
 * transcript is a verifier: anyone who captures one can test candidate keys
 * against it offline, without touching the network again. That is exactly why
 * the key comes from 160 random bits rather than from the user's gpodder.net
 * password: there is no candidate list to search. The client proving first is a
 * smaller, separate guard, so that merely connecting to a peer's port yields
 * nothing but a random nonce.
 *
 * After the handshake both sides derive per-direction session keys with HKDF and
 * seal every frame with AES-GCM under a strictly increasing counter nonce, so a
 * captured frame cannot be replayed — into this session or any later one, since
 * the keys are bound to nonces that will never recur.
 *
 * Every constant and label here is load-bearing for interoperating with the
 * desktop; `CryptoVectorsTest` pins them against vectors generated by the
 * Python implementation itself.
 */

const val PROTOCOL_VERSION: Int = 1
const val NONCE_LEN: Int = 16
const val KEY_LEN: Int = 32

private val CLIENT_LABEL = "aerialpod-lan-client".encodeToByteArray()
private val SERVER_LABEL = "aerialpod-lan-server".encodeToByteArray()
private val C2S_PREFIX = byteArrayOf('c'.code.toByte(), '2'.code.toByte(), 's'.code.toByte(), 0)
private val S2C_PREFIX = byteArrayOf('s'.code.toByte(), '2'.code.toByte(), 'c'.code.toByte(), 0)

private val PAIRING_SALT = "aerialpod-lan-pairing-v1".encodeToByteArray()
private val ROOT_INFO = "aerialpod-lan-root-key".encodeToByteArray()
private val SESSION_INFO = "aerialpod-lan-session-v1".encodeToByteArray()

enum class Role { CLIENT, SERVER }

/** Raised when AES-GCM authentication fails — the analogue of Python's `InvalidTag`. */
class InvalidTagException(message: String = "AES-GCM authentication failed") : Exception(message)

// ---------------------------------------------------------------- primitives
//
// Only these three touch a platform crypto provider. Everything above them —
// HKDF, the proofs, the sealing scheme — is common Kotlin, so there is exactly
// one implementation of the parts that have to agree with the desktop.

internal expect fun hmacSha256(key: ByteArray, data: ByteArray): ByteArray

internal expect fun aesGcmSeal(key: ByteArray, nonce: ByteArray, plaintext: ByteArray): ByteArray

/** @throws InvalidTagException on a forged, corrupted, reordered or replayed frame. */
internal expect fun aesGcmOpen(key: ByteArray, nonce: ByteArray, ciphertext: ByteArray): ByteArray

expect fun secureRandomBytes(n: Int): ByteArray

// ---------------------------------------------------------------- key schedule

/**
 * HKDF-SHA256 (RFC 5869), extract-then-expand.
 *
 * Hand-rolled rather than pulled from a platform API because the platforms
 * disagree about whether they have one at all: the JDK only gained `javax.crypto.KDF`
 * in Java 24, and Android has never exposed HKDF. It is thirty lines on top of
 * HMAC, and this way both platforms run the same thirty.
 */
internal fun hkdf(ikm: ByteArray, salt: ByteArray, info: ByteArray, length: Int): ByteArray {
    val prk = hmacSha256(salt, ikm)
    val out = ByteArray(length)
    var block = ByteArray(0)
    var offset = 0
    var counter = 1
    while (offset < length) {
        block = hmacSha256(prk, block + info + byteArrayOf(counter.toByte()))
        val take = minOf(block.size, length - offset)
        block.copyInto(out, offset, 0, take)
        offset += take
        counter++
    }
    return out
}

/**
 * Stretch the shared pairing secret into the handshake root key.
 *
 * A plain KDF, not a password hash: the input is already full-entropy, so
 * there is nothing for iteration count to defend against.
 */
fun channelKey(secret: ByteArray): ByteArray =
    hkdf(ikm = secret, salt = PAIRING_SALT, info = ROOT_INFO, length = KEY_LEN)

fun newNonce(): ByteArray = secureRandomBytes(NONCE_LEN)

fun clientProof(key: ByteArray, cn: ByteArray, sn: ByteArray): ByteArray =
    hmacSha256(key, CLIENT_LABEL + cn + sn)

fun serverProof(key: ByteArray, cn: ByteArray, sn: ByteArray): ByteArray =
    hmacSha256(key, SERVER_LABEL + cn + sn)

/** Constant-time compare — a proof check must not leak how far it matched. */
fun matches(expected: ByteArray, received: ByteArray): Boolean {
    if (expected.size != received.size) return false
    var diff = 0
    for (i in expected.indices) diff = diff or (expected[i].toInt() xor received[i].toInt())
    return diff == 0
}

/** (client->server key, server->client key) for this connection only. */
fun sessionKeys(key: ByteArray, cn: ByteArray, sn: ByteArray): Pair<ByteArray, ByteArray> {
    val material = hkdf(ikm = key, salt = cn + sn, info = SESSION_INFO, length = KEY_LEN * 2)
    return material.copyOfRange(0, KEY_LEN) to material.copyOfRange(KEY_LEN, KEY_LEN * 2)
}

// ---------------------------------------------------------------- sealing

/**
 * Both directions of an established session, from one end's point of view.
 *
 * Each direction has its own key and its own counter, and neither counter
 * ever resets — so every frame gets a unique nonce under a key that exists
 * only for this connection.
 */
class Sealer(role: Role, c2s: ByteArray, s2c: ByteArray) {
    private val outKey: ByteArray
    private val inKey: ByteArray
    private val outPrefix: ByteArray
    private val inPrefix: ByteArray
    private var outCounter = 0L
    private var inCounter = 0L

    init {
        if (role == Role.CLIENT) {
            outKey = c2s; inKey = s2c; outPrefix = C2S_PREFIX; inPrefix = S2C_PREFIX
        } else {
            outKey = s2c; inKey = c2s; outPrefix = S2C_PREFIX; inPrefix = C2S_PREFIX
        }
    }

    fun seal(plaintext: ByteArray): ByteArray {
        val nonce = nonceFor(outPrefix, outCounter)
        outCounter++
        return aesGcmSeal(outKey, nonce, plaintext)
    }

    /** @throws InvalidTagException on a forged, corrupted, reordered or replayed
     *  frame — the counter must match exactly. */
    fun open(ciphertext: ByteArray): ByteArray {
        val nonce = nonceFor(inPrefix, inCounter)
        inCounter++
        return aesGcmOpen(inKey, nonce, ciphertext)
    }

    private fun nonceFor(prefix: ByteArray, counter: Long): ByteArray {
        val nonce = ByteArray(12)
        prefix.copyInto(nonce, 0)
        for (i in 0 until 8) nonce[4 + i] = ((counter ushr ((7 - i) * 8)) and 0xFF).toByte()
        return nonce
    }
}
